ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Encoders -> vx, wz
    twist0: /wheel_twist
    twist0_config: [
      false, false, false,    # x y z
      false, false, false,    # roll pitch yaw
      true,  false, false,    # vx vy vz
      false, false, true,     # vroll vpitch vyaw (use wz from encoders)
      false, false, false
    ]
    twist0_queue_size: 50
    twist0_nodelay: true
    twist0_differential: false
    twist0_relative: false

    # IMU: use yaw orientation ONLY
    imu0: /imu/data
    imu0_config: [
      false, false, false,    # pos
      false, false, true,     # yaw
      false, false, false,    # vel
      false, false, false,    # angular vel (disable yaw rate here)
      false, false, false
    ]
    imu0_remove_gravitational_acceleration: true
    imu0_differential: false
    imu0_queue_size: 50

    sensor_timeout: 0.2
    print_diagnostics: true
