
twist_mux:
  ros__parameters:
    topics:
      - name: nav2
        topic: /cmd_vel
        timeout: 0.5
        priority: 50
      - name: avoid
        topic: /obstacle_avoidance/cmd_vel
        timeout: 0.3
        priority: 70
    locks:
      - name: estop
        topic: /obstacle_detected
        timeout: 0.0
        priority: 255